### ISSUE TITLE
Fail-over issue when root/admin disable

### ISSUE THREAD

**Issue by vividcolor12** [F5Networks/f5-cloud-failover-extension#101]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: v1.11.0 
- BIG-IP version: 15.1.4-0.21.47
- Cloud provider: Google Cloud Platform

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5> 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

The root/admin account was deactivated due to the security audit.

However, in case of fail-over, the existing Standby equipment becomes active, and the path must be delivered to the upper GCP side, but F5 equipment does not seem to be able to transmit the API normally API.

I have a question. Is it possible to modify the value in the RPM file?

Or can't I disable ADMIN, root?

========================================================
[I][119474][24 Apr 2022 23:28:27 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"GET","uri":"http://localhost:8100/mgmt/tm/cm/device-group","status":500,"from":"http://localhost:8100/tm/shared/bigip-failover-state"}
[I][119476][24 Apr 2022 23:29:27 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"GET","uri":"http://localhost:8100/mgmt/tm/cm/device-group","status":500,"from":"http://localhost:8100/tm/shared/bigip-failover-state"}

=========================================================

**Comment by sury99** [comment]
Did you get any answer on this?

**Comment by mikeshimkus** [comment]
@vividcolor12 Where and when did you see this log message? CFE doesn't make any request to either of the internal URLs in that message. 

That said, the admin account is required by CFE.

**Comment by vividcolor12** [comment]
@mikeshimkus restjavad-audit.log

The log was found in /var/log/restjavad-audit.log.
And I was force to standby in the Traffic-group to fail-over.

In F5, failover was performed normally, but in GCP, Alias IP was not transferred to the active equipment, so traffic did not come.

**Comment by mikeshimkus** [comment]
CFE should be logging to /var/log/restnoded/restnoded.log. Can you filter that on "f5-cloud-failover" and let us know the result?

The error you supplied isn't from CFE, and the status code is 500 which makes me think it's not related to authentication. However I would expect issues if the admin account is disabled since that is used internally by CFE and other automation toolchain packages.

**Comment by vividcolor12** [comment]
@mikeshimkus 

Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-cloud-failover/nodejs/providers/azure/cloud.js
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/constants.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/config.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/device.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/failover.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/logger.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/telemetry.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/util.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/validator.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:53 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/cloudFactory.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - severe: [LoaderWorker] JSHINT issues encountered in file /var/config/rest/iapps/f5-cloud-failover/nodejs/restWorkers/main.js, 2 errors
Wed, 15 Jun 2022 00:37:54 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-cloud-failover/nodejs/restWorkers/main.js: line 245, col 9, Expected a 'break' statement before 'case'.
Wed, 15 Jun 2022 00:37:54 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-cloud-failover/nodejs/restWorkers/main.js: line 280, col 9, Expected a 'break' statement before 'case'.
Wed, 15 Jun 2022 00:37:54 GMT - info: starting /shared/cloud-failover
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/schema/schemaUtils.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/aws/cloud.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/schema/formats.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/abstract/cloud.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/azure/cloud.js' is not a worker, skipping
Wed, 15 Jun 2022 00:37:54 GMT - info: [WorkerStateManager] Storage worker reports no key for: /shared/cloud-failover
Wed, 15 Jun 2022 00:37:58 GMT - finest: socket 187 closed

This is the log based on the latest file I have now.

It's hard to confirm right now.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if you would like additional assistance with this.
