### ISSUE TITLE
CFE doesn't work when multiple identities (UAIs) are assigned to the VM

### ISSUE THREAD

**Issue by jessed** [F5Networks/f5-cloud-failover-extension#105]
## Do you already have an issue opened with F5 support?
F5 support case: C3875597 / 1-8480354161

## Description
When multiple User-Assigned Identities are assigned to the VM the CFE cannot interact with the Azure API. Azure returns the following error:
"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"

The CFE does not have the ability to define which UAI should be used. This enhancement request is to add the ability to specify which identity should be used with the API calls. 

The issue can be worked-around by assigning all of the required roles to a single UAI and assigning that one UAI to the BIG-IP; however, that approach may not always be permitted by security policies.  

## Environment information
- Cloud Failover Extension Version:   v1.12.0
- BIG-IP version: v16.1.3
- Cloud provider: Azure

## Severity Level
N/A

Let me know if you would like any additional information regarding the environment or CFE configuration.

**Comment by G-gonzalezjimenez** [comment]
Hi, thanks for reporting this. We are tracking it internally with ID 3169

**Comment by shyawnkarim** [comment]
Closing. This issue was discussed internally and will not be implemented at this time.
