### ISSUE TITLE
GCP: Remove requirement for TARGET-INSTANCE object in AliasIP only use case

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#11]
(Issue moved from: https://github.com/f5devcentral/f5-cloud-failover-extension/issues/15)
Reported by: @f5-applebaum

Use case is that you would like to failover only AliasIps (vs Forwarding Rules).

Currently, the failover requires TARGET_INSTANCE objects to be created which is only needed for Forwarding Rules.

Workaround is creating target instance objects:

https://cloud.google.com/sdk/gcloud/reference/compute/target-instances/create

gcloud compute target-instances create NAME --instance=INSTANCE [--description=DESCRIPTION] [--instance-zone=INSTANCE_ZONE] [--zone=ZONE] [GCLOUD_WIDE_FLAG …]

**Comment by alaari-f5** [comment]
This is being tracked internally as:

AUTOSDK-195 - GCP: Remove requirement for TARGET-INSTANCE object in AliasIP only use case

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with release 1.2.
