### ISSUE TITLE
privateIpAddress Missing from /inspect request without an EIP

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-cloud-failover-extension#114]
## Do you already have an issue opened with F5 support?
No

## Description
When running a GET to /mgmt/shared/cloud-failover/inspect on a BIG-IP that does NOT have an EIP associated with a secondary private IP, the privateIpAddress is not populated in the "addresses" of the output. All other private IPs are listed if a Public EIP is associated. Once an EIP is associated to this private IP, then both public, private, and eni are included in the output. I would expect the private IP to be included in the "addresses" output.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.13.0
- BIG-IP version: 16.1.3.2
- Cloud provider: AWS

## Severity Level
5

**Comment by shyawnkarim** [comment]
I was able to verify this error and have filed a bug, internal ID ESECLDTPLT-3257.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 1.15.0](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.15.0).
