### ISSUE TITLE
Adding 2nd External NIC on Same Subnet not Working

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-cloud-failover-extension#115]
## Do you already have an issue opened with F5 support?
No

## Description
Customer is running AWS HA in same AZ. Customer needs a 2nd ext/public subnet because of the AWS 30 IP limit; they need more than 30 IP addresses for virtual servers. Added an additional NIC on the same subnet as the existing ext/public to each BIG-IP, added the following label:

- f5_cloud_failover_label: mydeployment <<< same as the rest of the CFE config
- f5_cloud_failover_nic_map: external2 <<< different to distinguish these new NICs from the original ext NICs

Created a new VLAN on each BIG-IP and assigned it to the new NIC.

Created a new VS using the new secondary IP that AWS assigned to the NIC.

Upon a failover event, All secondary IPs get moved over to the new active unit, but they all get moved to the same NIC on the new active unit. So IPs that were assigned to the original ext NIC and IPs that were assigned to the new ext NIC are now together on the same NIC. This is not the expected outcome, because we will then hit the 30 IP limit

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.13.0
- BIG-IP version: 16.1.3.2
- Cloud provider: AWS

**Comment by bradotlin** [comment]
If the 2 ext/pub NICs are using 2 different subnets, it works as expected.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. This configuration should be possible and I have created a bug ticket for it, ESECLDTPLT-3256.

**Comment by shyawnkarim** [comment]
Closing. A workaround was found offline with the customer.
