### ISSUE TITLE
NIC scopingTags are not optional

### ISSUE THREAD

**Issue by jcclive** [F5Networks/f5-cloud-failover-extension#124]
## Do you already have an issue opened with F5 support?
Yes, 00425520.

## Description

Documentation states that scopingTags on the NICs is the alternative configuration, but they are in fact mandatory.  Please update the documentation.

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#define-the-failover-addresses-in-azure

“Alternatively, if you are using the Discovery via Tag option, edit the declaration as shown below and tag your NICs. This will look for BIG-IPs Virtual Addresses (on traffic-group 1) and try to match them to Secondary IPs.”

Note the following error will appear in /var/log/restnoded/restnoded.log during a failover, inspect or dry-run:
Fri, 16 Jun 2023 14:19:15 GMT - finest: [f5-cloud-failover] Listing Network Interfaces
Fri, 16 Jun 2023 14:19:15 GMT - warning: [f5-cloud-failover] Problem with discovering network interfaces parsedNics

## Environment information
{
    "version": "1.14.0",
    "release": "0",
    "schemaCurrent": "1.14.0",
    "schemaMinimum": "0.9.1"
}
BigIP version 15.1.8.2
Azure

## Severity Level
Severity: 5

**Comment by mikeshimkus** [comment]
Thanks for reporting, we are tracking this with internal issue EC-290.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 1.15.0](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.15.0).
