### ISSUE TITLE
Can't parse schema to validate CFE declaration 

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-cloud-failover-extension#127]
## Description
When referencing the schema on Github in my JSON declaration in VS Code, I'm getting an error that the schema file fails to parse correctly.

Unable to parse content from 'https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/src/nodejs/schema/base_schema.json': Parse error at offset 6.

Could there be an error in the file itself?

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version:
- BIG-IP version: N/A
- Cloud provider: N/A

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by mikeshimkus** [comment]
Hi @grf5, what are you using to parse the schema? Using jsonlint.com shows it as valid JSON, and we use ajv to parse the config, which you'd think would make it fail on POST.

**Comment by grf5** [comment]
My apologies, I was parsing the output and not the payload.
