### ISSUE TITLE
Update link on Clouddocs

### ISSUE THREAD

**Issue by iluvpcs** [F5Networks/f5-cloud-failover-extension#13]
When one hits https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/# in the first paragraph is a reference GitHub for this project, but the URL is to the older clouddocs on github.com/f5devcenral archive of this project and not this repository.

**Comment by shyawnkarim** [comment]
Thanks for reporting this broken link. I've filed a ticket to get this link updated. Internal ID AUTOSDK-297.

**Comment by vtrippel** [comment]
Thank you for reporting this issue, it is now fixed.
