### ISSUE TITLE
GCP: CFE fails to update routes on a failover- when a project has more than 500 routes(globally) 

### ISSUE THREAD

**Issue by abhishek-batapati** [F5Networks/f5-cloud-failover-extension#14]
**Issue:** F5 CFE fails to update the user defined route on a failover

In our project we have more than 1500 global routes.

It might because of CFE making a GET API call to fetch all routes and then grep for the one with the right key:value pair in the description field.

But based on the below link GCP might return max 500 results per page.
https://cloud.google.com/compute/docs/reference/rest/v1/routes/list

This issue is currently a blocker for us as we have seen multiple failovers in our env and all of them have failed.

**Comment by abhishek-batapati** [comment]
Hi CFE Team,

This issue is seen with forwardingrules as well if a region has more than 500 rules.
We have few regions which has more than 2500 rules.
Failover in such regions are failing to update the fwd rules as well.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with release 1.3.
