### ISSUE TITLE
Documentation: example IAM role for AWS instructions is bad

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#144]
## Do you already have an issue opened with F5 support?
No, customer called their account team for support

## Description
If a customer copies and pastes the IAM role from [this documentation](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#iam-role-example-declaration), they are going to have invalid JSON

- There are at least 2 instances where `\*` should be `"*"` in the JSON that is documented
- A customer doing this manually though the AWS web console is likely to want the JSON to create a policy, not a role. Providing the JSON to create a **role** (and not a **policy**) confused my customer.

CFE troubleshooting is **hard** so anything to make this easier would be great.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: documentation

#

**Comment by mikeshimkus** [comment]
@mikeoleary Updated the docs to show a valid JSON policy instead of the role config: https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#iam-role-example-declaration

LMK if this helps.

**Comment by mikeoleary** [comment]
thank you @mikeshimkus , this looks like it will help. For now, I think this is the best I can ask for. I'll close this issue.
