### ISSUE TITLE
ECONNREFUSED in logs showing unknown public IP addresses

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-cloud-failover-extension#16]
I'm trying to make the initial configuration declaration using CFE v1.2 and I'm seeing this error in the logs:

Thu, 30 Apr 2020 17:25:11 GMT - finest: socket 200 closedThu, 30 Apr 2020 17:25:20 GMT - severe: [f5-cloud-failover] Failover initialization failed: connect ECONNREFUSED 40.71.13.226:443 Error: connect ECONNREFUSED 40.71.13.226:443

Thu, 30 Apr 2020 17:23:56 GMT - severe: [f5-cloud-failover] Sending telemetry failed: Unable to register device: connect ECONNREFUSED 35.199.173.84:443

I've confirmed that the metadata-route management route exists. Perhaps it's redirecting to these public IPs?

Also getting the error on 52.239.155.132.

**Comment by grf5** [comment]
This was caused by the API connections being sourced from the external interfaces on the BIG-IPs. In my setup, all Azure resources are routed through the BIG-IP and then by default UDR route to the Express Route, which does not provide Internet connectivity. We fixed this by downloading the list of MSFT service subnets and routing them to the Internet as UDRs on the Azure route table. See [https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-ip-addresses]. The only way I could see this addressed from the BIG-IP side is either a mechanism for automating the subnet query (see link above) and creating those management-routes dynamically or finding a way to pin the API traffic to the management interface.

**Comment by tjvreugdenhil** [comment]
We ran into a similar situation and same error message. For right now, we edited the F5 default route to point out the internal gateway of which the F5 could access AWS. (because the IP's are dynamic there is no way to create host routes)

**Comment by grf5** [comment]
For Azure, the right way to do this is to grab the list of API management addresses from https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-ip-addresses and create UDRs for those IPs to point towards the Internet since our default routing to the Express Route is which broke the connectivity. While having API failover traffic pinned to the management interface on the BIG-IP would help my situation, it's not a universal fix for other cloud platforms or other configurations.

**Comment by shyawnkarim** [comment]
Closing. Please feel free to reopen if more attention is needed.
