### ISSUE TITLE
[f5-cloud-failover] Recovery operations are empty, advise reset via the API "failoverOperations":{"addresses":null,"routes":null}}

### ISSUE THREAD

**Issue by tjvreugdenhil** [F5Networks/f5-cloud-failover-extension#17]
https://devcentral.f5.com/s/articles/Using-VPC-Endpoints-with-Cloud-Failover-Extension

We Created S3 Endpoint and added it to both F5 DMZ and Trust AWS Subnets with full policy access

Created EC2 EndPoint, enabled DNS for endpoint, and attached the bigip internal security group. 

Getting a "Recovery operations are empty" error. 
[root@ip-10-10-8-28:Standby:In Sync] config # tail -f /var/log/restnoded/restnoded.log
Mon, 04 May 2020 21:04:17 GMT - info: [f5-cloud-failover] Performing failover - execute
Mon, 04 May 2020 21:04:17 GMT - warning: [f5-cloud-failover] Performing Failover - recovery
Mon, 04 May 2020 21:04:17 GMT - severe: [f5-cloud-failover] Recovery operations are empty, advise reset via the API Error: Recovery operations are empty, advise reset via the API
  at FailoverClient._getRecoveryOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/failover.js:373:19)
  at _getDeviceObjects.then.then.then (/var/config/rest/iapps/f5-cloud-failover/nodejs/failover.js:124:33)
  at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
  at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)
  at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:133:16)
  at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
  at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
  at runCallback (timers.js:794:20)
  at tryOnImmediate (timers.js:752:5)
  at processImmediate [as _immediateCallback] (timers.js:729:5)
  
 ================================================================== 
The Following JSON declartion is successful from both F51 and F52.

{
    "message": "success",
    "declaration": {
        "class": "Cloud_Failover",
        "environment": "aws",
        "externalStorage": {
            "scopingTags": {
                "f5_cloud_failover_label": "bigip-nonprod"
            }
        },
        "failoverAddresses": {
            "enabled": true,
            "scopingTags": {
                "f5_cloud_failover_nic_map_eth1": "NonProd-eth1-external",
                "f5_cloud_failover_nic_map_eth2": "NonProd-eth2-internal",
                "f5_cloud_failover_nic_map_eth3": "NonProd-eth3-internal2"
            },
            "failoverRoutes": {
                "enabled": true,
                "scopingTags": {
                    "f5_cloud_failover_label": "bigip-nonprod-prod"
                },
                "scopingAddressRanges": [
                    {
                        "range": "10.10.116.0/24, 10.10.117.0/24, 10.200.116.0/24, "
                    }
                ],
                "defaultNextHopAddresses": {
                    "discoveryType": "static",
                    "items": [
                        "10.200.116.105",
                        "10.200.116.116",
                        "10.10.116.88",
                        "10.10.116.56",
                        "10.10.117.94",
                        "10.10.117.232"
                    ]
                }
            },
            "controls": {
                "class": "Controls",
                "logLevel": "silly"
            }
        },
        "schemaVersion": "1.2.0"
    }
}

And the dig does return a valid internal IP of the S3 Endpoint:
[root@ip-10-10-8-10:Standby:In Sync] config # dig ec2.us-east-2.amazonaws.com
hmac_link.c:350: FIPS mode is 1: MD5 is only supported if the value is 0.
Please disable either FIPS mode or MD5.
; <<>> DiG 9.11.8 <<>> ec2.us-east-2.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63858
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;ec2.us-east-2.amazonaws.com.  IN   A
;; ANSWER SECTION:
ec2.us-east-2.amazonaws.com. 60 IN   A    10.200.116.158
;; Query time: 3 msec
;; SERVER: 10.10.112.2#53(10.10.112.2)
;; WHEN: Mon May 04 16:05:47 CDT 2020
;; MSG SIZE rcvd: 61

#Check F5 metadata service on both F52 instance so the IAM role can be applied
[root@ip-10-10-8-28:Active:In Sync] config # curl http://169.254.169.254/latest/meta-data/iam/info
{
  "Code" : "Success",
  "LastUpdated" : "2020-05-05T03:05:01Z",
  "InstanceProfileArn" : "arn:aws:iam::471729006672:instance-profile/bigip-nonprod-bigipServiceDiscoveryProfile-7C6M9RR6HBAJ",
  "InstanceProfileId" : "AIPAW3VJ5NBIKL4YLXK7Y"

#AWS API is reachable from F52: 
[root@ip-10-10-8-28:Standby:In Sync] config #  curl -sI https://ec2.us-east-2.amazonaws.com | grep Server
Server: AmazonEC2

#Check F5 metadata service on both F51 instance so the IAM role can be applied
[root@ip-10-10-8-10:Active:In Sync] config # curl http://169.254.169.254/latest/meta-data/iam/info
{
  "Code" : "Success",
  "LastUpdated" : "2020-05-05T03:01:26Z",
  "InstanceProfileArn" : "arn:aws:iam::471729006672:instance-profile/bigip-nonprod-bigipServiceDiscoveryProfile-7C6M9RR6HBAJ",
  "InstanceProfileId" : "AIPAW3VJ5NBIKL4YLXK7Y"

#AWS API is reachable from F52: 
[root@ip-10-10-8-10:Active:In Sync] config #  curl -sI https://ec2.us-east-2.amazonaws.com | grep Server
Server: AmazonEC2

**Comment by tjvreugdenhil** [comment]
Here is the "f5cloudfailoverstate.json" in the F5 S3 bucket:
{"taskState":"FAILED","message":"Failover failed because Recovery operations are empty, advise reset via the API","timestamp":"2020-05-05T17:03:39.568Z","instance":"ip-10-10-8-10.us-east-2.compute.internal","failoverOperations":{"addresses":null,"routes":null}}

**Comment by tjvreugdenhil** [comment]
The issue was resolved by resetting state from API documentation.

**Comment by grf5** [comment]
I had this same issue and resetting state helped me as well. Doc link for doing so: https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/apidocs.html

**Comment by shyawnkarim** [comment]
Documentation for these questions was added in Release 1.4 to our Cloud Failover Extension FAQ.
