### ISSUE TITLE
Azure: CFE modifies routes whose nextHop doesn't belong to BIG-IP

### ISSUE THREAD

**Issue by keith66fuller** [F5Networks/f5-cloud-failover-extension#18]
### CFE v.1.2.0
CFE will modify a route, changing its next hop address to one of the BIG-IP local addresses even if the current next hop address on the route doesn't belong to BIG-IP, i.e. the address isn't in f5_self_ips.

For instance

- Route table tagged with "**f5_self_ips**":"192.168.56.37,192.168.56.38"

- Route in route table with prefix 10.0.0.0/8 and with next hop 192.168.56.36

192.168.56.36 is not BIG-IP and is not in **f5_self_ips**

CFE will change next hop of route to either 192.168.56.37 or 192.168.56.38.

**Comment by jsevedge** [comment]
@keith66fuller What does your CFE configuration look like?  Is 10.0.0./8 in `failoverRoutes.scopingAddressRanges`?  I would assume yes as that is what determines which routes in the route table will be updated.  CFE does not check what address is set as the next hop, it only checks *if* it needs to be updated and if so which next hop should be used (from f5_self_ips OR hardcoded in the CFE configuration if discovery type is static)

**Comment by f5-chidambaram** [comment]
Closing this now. Reopen if you have any concerns.
