### ISSUE TITLE
Dynamically created management routes

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-cloud-failover-extension#19]
RFE idea, it would be awesome if CFE created a management-route dynamically if ECONREFUSED is encountered and retries the connection. This could be a simple flag in the config such as "dynamic_mgmt_route_creation":"enabled". It would follow the same gateway as the default management route with a /32 network using the IP in the error message.

**Comment by grf5** [comment]
This was a result of an issue where the BIG-IP VE data plane interfaces did not have Internet access. All traffic in/out of Azure is sent on-prem via Express Route. We had to add a bunch of host mgmt routes to the BIG-IP to ensure that Azure API traffic would egress the management-route. This is the list of tmsh commands we used: https://github.com/grf5/tmos_azure_api_host_routes ... which were derived from the Microsoft published list of Azure IP Public IP ranges.

**Comment by shyawnkarim** [comment]
Thanks for contacting us with this enhancement request. I've added it to our backlog, internal ID AUTOSDK-317.

**Comment by nmenant** [comment]
@f5-chidambaram F5 has decided not to take the decision to implement missing route dynamically since it could lead to outage. CFE shouldn't be allowed to update routes on its own if it's missing. However we work on providing a feature that would highlight misconfiguration. AUTOSDK-429

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.6](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.6.0).
