### ISSUE TITLE
RFE: CFE to support Azure Private Endpoints for Storage Account

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#2]
(Issue recreated from https://github.com/f5devcentral/f5-cloud-failover-extension/issues/26)
Reported By: @tewfikm 

Title : Request for Enhancement : CFE to support Azure Private Endpoints for Storage Account

Details:
For security reasons, customer is asking CFE to avoid performing API calls to Azure Public Endpoints.

Current CFE Azure provider is performing DNS resolution to Azure Storage account using connection String to Storage Account Public endpoint.

ASK:
CFE to Support Private Endpoint for storage accounts, by:

giving option to configure storage account to switch to Private Endpoint on the VNET CFE is installed
denying public access using storage FW

**Comment by alaari-f5** [comment]
Thanks for submitting this enhancement. I've created internal issue ID AUTOSDK-273 and have added it to our backlog.

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.8](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.8.0).
