### ISSUE TITLE
document f5_cloud_failover_vips attribute for AWS

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-cloud-failover-extension#20]
Hi,
Clouddoc states that for AWS :

For Across Network Topology¶
If provisioning Across Network Topology, you will need to:

Create two sets of tags for Elastic IP addresses:

a special key called f5_cloud_failover_vips that contains a comma-separated list of addresses mapping to a private IP address on each instance in the cluster that the Elastic IP is associated with. For example: 10.0.0.10,10.0.0.11

ASK:

Could you please update API Docs with this parameter ?

Provide sample example for 2x EIP and 4 privates IPs ?

Thanks

**Comment by shyawnkarim** [comment]
I've created a document enhancement for this, internal ID AUTOSDK-320.

**Comment by tewfikm** [comment]
Hi @shyawnkarim 
Do you have an ETA please ? 
Customer is chasing.
Many thanks

**Comment by nmenant** [comment]
This is done: 
![image](https://user-images.githubusercontent.com/13098758/93743317-259d2580-fbf0-11ea-9945-f19b133bb152.png)

@f5-chidambaram  please close

**Comment by shyawnkarim** [comment]
This addition to our documentation was included with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).
