### ISSUE TITLE
Improved visibility/telemetry data of F5 CFE operations

### ISSUE THREAD

**Issue by tjvreugdenhil** [F5Networks/f5-cloud-failover-extension#21]
Enhancement request: 

Request to improve visibility/telemetry data of F5 CFE operations whether in a location in AWS or in the F5 /var/log/restnoded/restnoded.log
(the “silly” log verbose method only displays the following when working). 

```
Tue, 26 May 2020 23:25:08 GMT - info: [f5-cloud-failover] Performing Failover - discovery
Tue, 26 May 2020 23:25:09 GMT - info: [f5-cloud-failover] Performing Failover - update
Tue, 26 May 2020 23:25:09 GMT - info: [f5-cloud-failover] Association of Elastic IP addresses not required
Tue, 26 May 2020 23:25:10 GMT - info: [f5-cloud-failover] Addresses reassociated successfully
Tue, 26 May 2020 23:25:10 GMT - info: [f5-cloud-failover] Failover Complete
```

**Comment by jsevedge** [comment]
@tjvreugdenhil There should definitely be more logging that that at the silly level.  Did you update the log level using the controls block as shown [here](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/example-declarations.html#example-declaration-setting-the-log-level) and rePOSTed to the CFE config endpoint?

If so on the initial set of log level it only applies to the active BIG-IP, the standby BIG-IP will get synced config but will not update the system log level unless a `bigstart restart restnoded` is performed from the shell.  Try that as well and see if it makes a difference?

**Comment by tjvreugdenhil** [comment]
I did update the controls block and posted the declaration successfully to both F5's. I did just restart restnoded and tried again, and still do not see any verbose logs. Below is my declaration. 

[admin@ip-10-10-8-32:Standby:In Sync] ~ # bigstart restart restnoded
[admin@ip-10-10-8-32:Standby:In Sync] ~ # tail -f /var/log/restnoded/restnoded.log
Sun, 31 May 2020 22:34:49 GMT - finest: socket 117 closed
Sun, 31 May 2020 22:34:49 GMT - finest: socket 74 closed
Sun, 31 May 2020 22:34:49 GMT - finest: socket 40 closed
Sun, 31 May 2020 22:35:23 GMT - finest: socket 184 opened
Sun, 31 May 2020 22:35:24 GMT - info: [f5-cloud-failover] Performing failover - execute
Sun, 31 May 2020 22:35:26 GMT - info: [f5-cloud-failover] Performing Failover - discovery
Sun, 31 May 2020 22:35:27 GMT - info: [f5-cloud-failover] Performing Failover - update
Sun, 31 May 2020 22:35:27 GMT - info: [f5-cloud-failover] Association of Elastic IP addresses not required
Sun, 31 May 2020 22:35:28 GMT - info: [f5-cloud-failover] Addresses reassociated successfully
Sun, 31 May 2020 22:35:28 GMT - info: [f5-cloud-failover] Failover Complete
Sun, 31 May 2020 22:35:33 GMT - finest: socket 184 closed
^C
[admin@ip-10-10-8-32:Active:In Sync] ~ #


```
{
	"class": "Cloud_Failover",
	"environment": "aws",
	"externalStorage": {
		"scopingTags": {
			"f5_cloud_failover_label": "bigip-nonprod"
		}
	},
	"failoverAddresses": {
		"enabled": true,
		"scopingTags": {
			"f5_cloud_failover_label": "bigip-nonprod"
		},
		"failoverRoutes": {
			"enabled": true,
			"scopingTags": {
				"f5_cloud_failover_label": "bigip-nonprod"
			},
			"scopingAddressRanges": [
			{
				"range": "10.10.116.0/24",
			    "nextHopAddresses": {
					"discoveryType": "static",
					"items": [
					"10.10.116.88",
					"10.10.116.56"
					]
				}
			},
				{
				"range": "10.10.117.0/24",
			    "nextHopAddresses": {
					"discoveryType": "static",
					"items": [
					"10.10.117.94",
					"10.10.117.232"
					]
				}
			},
				{
				"range": "10.200.116.0/24",
			    "nextHopAddresses": {
					"discoveryType": "static",
					"items": [
					"10.200.116.105",
					"10.200.116.116"
					]
				}
			}
		],
			"defaultNextHopAddresses": {
				"discoveryType": "static",
				"items": [
					"10.10.116.88",
					"10.10.116.56",
					"10.10.117.94",					
					"10.10.117.232",
					"10.200.116.105",
					"10.200.116.116"
				]
        }
    },
    "controls": {
      "class": "Controls",
      "logLevel": "silly"
    }
  }
}
```

**Comment by shyawnkarim** [comment]
It looks like you have the "controls" nested inside "failoverAddresses". Can you try moving the "controls" outside of "failoverAddresses" so that is at the same level?

**Comment by tjvreugdenhil** [comment]
Good catch - that was it :)
