### ISSUE TITLE
Documentation: example GCP route has extra 24 mask x.x.x.x-24-24

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-cloud-failover-extension#23]
The clouddocs have an example to create a GCP route, but the cidr mask is shown twice so command will fail.

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/gcp.html#label-the-user-defined-routes-in-gcp

currently (wrong)
```
 gcloud compute routes create example-route --destination-range=192.168.1.0/24/24 --network=example-network --next-hop-address=192.0.2.10 --description='f5_cloud_failover_labels={"f5_cloud_failover_label":"mydeployment"}'
```

should be
```
 gcloud compute routes create example-route --destination-range=192.168.1.0/24 --network=example-network --next-hop-address=192.0.2.10 --description='f5_cloud_failover_labels={"f5_cloud_failover_label":"mydeployment"}'
```

**Comment by shyawnkarim** [comment]
Thanks for reporting this error in our documentation. We are tracking this internally with ID AUTOSDK-347.

**Comment by f5-chidambaram** [comment]
Done in CFE 1.4
