### ISSUE TITLE
A POST on /trigger with the body {"action": "execute"} does not trigger CFE or DSC failover operation

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-cloud-failover-extension#24]
## Abstract
A POST on /trigger with the body {"action": "execute"} does not trigger failover

## description
when you Post a { "action": "execute" } on https://{{bigip1}}/mgmt/shared/cloud-failover/trigger, CFE return   a  "message": "Failover Complete" but no failover operation happens and no action on DSC.

{
    "taskState": "SUCCEEDED",
    "message": "Failover Complete",
    "timestamp": "2020-06-04T15:04:10.306Z",
    "instance": "AL-P2-F51-test.com",
    "failoverOperations": {
        "addresses": {},
        "routes": {}
    }
}

the only action that triggers CFE is a DSC failover (via GUI, CLI or iControl API)

## ASK
Please clarify behavior of POST /trigger function or fix

## severity
3

**Comment by JeffGiroux** [comment]
Agreed, having POST /trigger available in Postman collection is confusing. It does NOT work by itself. The /trigger endpoint is called by the natural failover event of the F5 units where other things happen too...and /trigger POST gets called.

In my experience, DO NOT run POST /trigger. But...you can do GET /trigger which shows very helpful info similar to what you might see after scrubbing /var/log/restnoded logs...and the /trigger GET also shows you similar info that is dumped into the cloud storage bucket failover json file.

I think the postman collection should remove POST /trigger as a user SHOULD NEVER run it manually. Also, detailed documentation should be added around the use of /trigger especially in the troubleshooting section.

**Comment by shyawnkarim** [comment]
@JeffGiroux is correct. We are tracking this documentation fix internally with ID AUTOSDK-348.

**Comment by tewfikm** [comment]
@shyawnkarim @JeffGiroux 
The CFE API schema describes the POST /trigger function as a valid function which is also documented in the associated OpenAPI Swagger file.
See here:
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/apidocs.html

Decision needs to be made to wheither to remove this Post function (+ amend documentation and Schema) or to fix it in order to behave like expected in the product specification.

Thanks

**Comment by shyawnkarim** [comment]
Closing.

Documentation for the /trigger endpoint was added in Release [1.6](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.6.0).
