### ISSUE TITLE
documentation for AWS instructions for tagging NICs

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#25]
The current clouddocs for AWS instructions say "Choose the set of instructions to follow based on whether you are provisioning for same network or across network." Then, if you look at the section called [For Across Network Topology](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#for-across-network-topology) it only says you need to tag Elastic IP's. From my experience, you must also tag NIC's. For example, I am updating a route only (no EIP remapping) so the NIC tagging that is mentioned for "Same Network Topology" is also required for Across Network.

**Comment by shyawnkarim** [comment]
Yes, the nics should also be tagged. We are tracking this documentation fix internally with ID AUTOSDK-349.

**Comment by f5-chidambaram** [comment]
Done in CFE 1.4
