### ISSUE TITLE
[Doc]Broken link

### ISSUE THREAD

**Issue by nmenant** [F5Networks/f5-cloud-failover-extension#28]
The link to retrieve the postman collection is broken on this page (404 Not Found): 

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/postman-collection.html

**Comment by jsevedge** [comment]
The correct link is https://github.com/F5Networks/f5-cloud-failover-extension/releases/latest/download/postmanCollection.json

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue with our documentation. We are now tracking this documentation fix internally with ID AUTOSDK-361.

**Comment by shyawnkarim** [comment]
Closing.

The documentation was corrected with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).

**Comment by jmcalalang** [comment]
This is broken again, it looks like the clouddocs link is pointing at: 

https://github.com/F5Networks/f5-cloud-failover-extension/releases/download/v1.8.0/postmanCollection.json

but now in 1.8 its a .zip

https://github.com/F5Networks/f5-cloud-failover-extension/releases/download/v1.8.0/postman-collection.zip

**Comment by shyawnkarim** [comment]
Thanks for reporting this broken link. I've filed ticket, AUTOSDK-531,  to fix the link.

**Comment by shyawnkarim** [comment]
This issue was fixed with [Release 1.9](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.9.0).
