### ISSUE TITLE
AWS HA cross AZ multi VIP - regression of iApp aws_advanced_ha

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-cloud-failover-extension#29]
**Regression**
Related to issue #20, CFE cannot handle AWS HA cross AZ for multiples VIPs. `aws_advanced_ha.v1.4.0rc5` had this capability.

**Feature Request**
manage multiple Virtual Address to failover in a cross AZ use case on AWS (and associated documentation)

**Comment by shyawnkarim** [comment]
CFE is able to failover multiple VIPS cross AZ. The documentation for it can be seen [here](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#aws-failover-event-diagram).

**Comment by nergalex** [comment]
Thx
