### ISSUE TITLE
GCP: Failover is broken when dst is 'ANY' in a VS

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#3]
(Issue moved from https://github.com/f5devcentral/f5-cloud-failover-extension/issues/25)
Reported By: @abhishek-batapati 

We have multiple VS in our configuration with few VS having destination as 'ANY'(0.0.0.0/0).
VS with dst 'ANY' is used for source NAT.

When we trigger a failover, it is failing because of VS with dst as 'ANY'. We would have expect it to skip this VS for failover.

Error log:
Mon, 06 Apr 2020 04:17:41 GMT - info: [f5-cloud-failover] Performing failover - execute
Mon, 06 Apr 2020 04:17:41 GMT - info: [f5-cloud-failover] Performing Failover - discovery
Mon, 06 Apr 2020 04:17:42 GMT - severe: [f5-cloud-failover] failover.execute() error: ipaddr: the address has neither IPv6 nor IPv4 format Error: ipaddr: the address has neither IPv6 nor IPv4 format
at Object.ipaddr.parse (/var/config/rest/iapps/f5-cloud-failover/node_modules/ipaddr.js/lib/ipaddr.js:632:13)
at ipsFilter.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:516:51)
at Array.forEach ()
at ips.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:512:23)
at Array.forEach ()
at Cloud._matchIps (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:505:13)
at vm.networkInterfaces.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:640:51)
at Array.forEach ()
at theirVms.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:636:34)
at Array.forEach ()
at Cloud._discoverNicOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:634:18)
at Cloud._discoverAddressOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:590:18)
at _getVmsByTags.then (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:173:33)
at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)
at Promise._fulfill (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:638:18)
at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:582:21)
at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)

**Comment by alaari-f5** [comment]
Can you change the logging level to silly via the instructions on this page and then post your output again?

**Comment by alaari-f5** [comment]
Please find the output below after changing log level to silly.

Tue, 07 Apr 2020 17:54:48 GMT - fine: [f5-cloud-failover] HTTP Request - POST /trigger
Tue, 07 Apr 2020 17:54:48 GMT - fine: [f5-cloud-failover] Initializing failover class
Tue, 07 Apr 2020 17:54:48 GMT - fine: [f5-cloud-failover] config: {"class":"Cloud_Failover","environment":"gcp","externalStorage":{"scopingTags":{"goog-dm":"dev1-sjc1-ng"}},"failoverAddresses":{"scopingTags":{"goog-dm":"dev1-sjc1-ng"}},"failoverRoutes":{"scopingTags":{"goog-dm":"dev1-sjc1-ng"},"scopingAddressRanges":[{"range":"0.0.0.0/0"}],"defaultNextHopAddresses":{"discoveryType":"static","items":["192.168.0.130","192.168.0.131"]}},"controls":{"class":"Controls","logLevel":"silly"},"schemaVersion":"1.1.0"}
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: artifacts.saasdev-sed-wss-hp.appspot.com bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-cs1-cas-postconfig bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-dev-cas-db bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-dev-cas-postconfig bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-dev-pod-tp bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-dev1-cas-postconfig bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: bkt-mv1-cas-postconfig bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: dev-cas-images bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-cs1-cs1dc bucket labels: [{"f5_cloud_failover_label":"cs1-cs1dc","goog-dm":"cs1-cs1dc"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev-acdc bucket labels: [{"f5_cloud_failover_label":"dev-acdc","goog-dm":"dev-acdc"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-devdc1 bucket labels: [{"f5_cloud_failover_label":"dev1-devdc1","goog-dm":"dev1-devdc1"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-devdc1-ng bucket labels: [{"f5_cloud_failover_label":"dev1-devdc1-ng","goog-dm":"dev1-devdc1-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-mv1 bucket labels: [{"goog-dm":"dev1-mv1","f5_cloud_failover_label":"dev1-mv1"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-mv1-ng bucket labels: [{"goog-dm":"dev1-mv1-ng","f5_cloud_failover_label":"dev1-mv1-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-nyam-dc bucket labels: [{"goog-dm":"dev1-nyam-dc","f5_cloud_failover_label":"dev1-nyam-dc"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-qa1 bucket labels: [{"goog-dm":"dev1-qa1","f5_cloud_failover_label":"dev1-qa1"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-sjc1 bucket labels: [{"f5_cloud_failover_label":"dev1-sjc1","goog-dm":"dev1-sjc1"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-sjc1-ng bucket labels: [{"goog-dm":"dev1-sjc1-ng","f5_cloud_failover_label":"dev1-sjc1-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev1-tp1 bucket labels: [{"f5_cloud_failover_label":"dev1-tp1","goog-dm":"dev1-tp1"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-devdc6 bucket labels: [{"goog-dm":"dev7-devdc6","f5_cloud_failover_label":"dev7-devdc6"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-devdc6-ng bucket labels: [{"f5_cloud_failover_label":"dev7-devdc6-ng","goog-dm":"dev7-devdc6-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-devdc7 bucket labels: [{"f5_cloud_failover_label":"dev7-devdc7","goog-dm":"dev7-devdc7"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-devdc7-ng bucket labels: [{"f5_cloud_failover_label":"dev7-devdc7-ng","goog-dm":"dev7-devdc7-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-qa7 bucket labels: [{"goog-dm":"dev7-qa7","f5_cloud_failover_label":"dev7-qa7"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-qa7-ng bucket labels: [{"goog-dm":"dev7-qa7-ng","f5_cloud_failover_label":"dev7-qa7-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-dev7-sacheen bucket labels: [{"f5_cloud_failover_label":"dev7-sacheen","goog-dm":"dev7-sacheen"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: f5-bigip-storage-tp1-dcw1-ng bucket labels: [{"goog-dm":"tp1-dcw1-ng","f5_cloud_failover_label":"tp1-dcw1-ng"}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: saasdev-sed-wss-hp.appspot.com bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: saasdev-sed-wss-hpcai bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: sed-gcp-iam-development bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: staging.saasdev-sed-wss-hp.appspot.com bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] bucket name: us.artifacts.saasdev-sed-wss-hp.appspot.com bucket labels: [{}]
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] deployment bucket name: f5-bigip-storage-dev1-sjc1-ng
Tue, 07 Apr 2020 17:54:48 GMT - finest: [f5-cloud-failover] Getting GCP resources
Tue, 07 Apr 2020 17:54:49 GMT - finest: [f5-cloud-failover] GCP resources have been collected; gcp provider initialization is completed.
Tue, 07 Apr 2020 17:54:50 GMT - finest: [f5-cloud-failover] Download stateFile: {"taskState":"FAILED","message":"Failover failed because of failover.execute() error: ipaddr: the address has neither IPv6 nor IPv4 format Error: ipaddr: the address has neither IPv6 nor IPv4 format\n at Object.ipaddr.parse (/var/config/rest/iapps/f5-cloud-failover/node_modules/ipaddr.js/lib/ipaddr.js:632:13)\n at ipsFilter.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:516:51)\n at Array.forEach ()\n at ips.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:512:23)\n at Array.forEach ()\n at Cloud._matchIps (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:505:13)\n at vm.networkInterfaces.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:640:51)\n at Array.forEach ()\n at theirVms.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:636:34)\n at Array.forEach ()\n at Cloud._discoverNicOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:634:18)\n at Cloud._discoverAddressOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:590:18)\n at _getVmsByTags.then (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:173:33)\n at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)\n at Promise._fulfill (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:582:21)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)","timestamp":"2020-04-06T04:17:42.650Z","instance":"bigip2-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{"addresses":null,"routes":null}}
Tue, 07 Apr 2020 17:54:50 GMT - finest: [f5-cloud-failover] taskState: {"taskState":"FAILED","message":"Failover failed because of failover.execute() error: ipaddr: the address has neither IPv6 nor IPv4 format Error: ipaddr: the address has neither IPv6 nor IPv4 format\n at Object.ipaddr.parse (/var/config/rest/iapps/f5-cloud-failover/node_modules/ipaddr.js/lib/ipaddr.js:632:13)\n at ipsFilter.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:516:51)\n at Array.forEach ()\n at ips.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:512:23)\n at Array.forEach ()\n at Cloud._matchIps (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:505:13)\n at vm.networkInterfaces.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:640:51)\n at Array.forEach ()\n at theirVms.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:636:34)\n at Array.forEach ()\n at Cloud._discoverNicOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:634:18)\n at Cloud._discoverAddressOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:590:18)\n at _getVmsByTags.then (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:173:33)\n at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)\n at Promise._fulfill (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:582:21)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)","timestamp":"2020-04-06T04:17:42.650Z","instance":"bigip2-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{"addresses":null,"routes":null}}
Tue, 07 Apr 2020 17:54:50 GMT - info: [f5-cloud-failover] Performing failover - execute
Tue, 07 Apr 2020 17:54:50 GMT - finest: [f5-cloud-failover] State file data: {"taskState":"FAILED","message":"Failover failed because of failover.execute() error: ipaddr: the address has neither IPv6 nor IPv4 format Error: ipaddr: the address has neither IPv6 nor IPv4 format\n at Object.ipaddr.parse (/var/config/rest/iapps/f5-cloud-failover/node_modules/ipaddr.js/lib/ipaddr.js:632:13)\n at ipsFilter.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:516:51)\n at Array.forEach ()\n at ips.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:512:23)\n at Array.forEach ()\n at Cloud._matchIps (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:505:13)\n at vm.networkInterfaces.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:640:51)\n at Array.forEach ()\n at theirVms.forEach (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:636:34)\n at Array.forEach ()\n at Cloud._discoverNicOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:634:18)\n at Cloud._discoverAddressOperations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:590:18)\n at _getVmsByTags.then (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:173:33)\n at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)\n at Promise._fulfill (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:582:21)\n at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)","timestamp":"2020-04-06T04:17:42.650Z","instance":"bigip2-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{"addresses":null,"routes":null}}
Tue, 07 Apr 2020 17:54:50 GMT - info: [f5-cloud-failover] Performing Failover - recovery
Tue, 07 Apr 2020 17:54:50 GMT - finest: [f5-cloud-failover] Data will be uploaded to f5cloudfailoverstate.json: {"taskState":"RUNNING","message":"Failover running","timestamp":"2020-04-07T17:54:50.651Z","instance":"bigip1-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{}}
Tue, 07 Apr 2020 17:54:50 GMT - warning: [f5-cloud-failover] Recovering previous task: {"addresses":null,"routes":null}
Tue, 07 Apr 2020 17:54:50 GMT - finest: [f5-cloud-failover] Data will be uploaded to f5cloudfailoverstate.json: {"taskState":"RUNNING","message":"Failover running","timestamp":"2020-04-07T17:54:50.982Z","instance":"bigip1-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{"addresses":null,"routes":null}}
Tue, 07 Apr 2020 17:54:51 GMT - info: [f5-cloud-failover] Performing Failover - update
Tue, 07 Apr 2020 17:54:51 GMT - fine: [f5-cloud-failover] recoverPreviousTask: true
Tue, 07 Apr 2020 17:54:51 GMT - fine: [f5-cloud-failover] addressDiscovery: null
Tue, 07 Apr 2020 17:54:51 GMT - fine: [f5-cloud-failover] routeDiscovery: null
Tue, 07 Apr 2020 17:54:51 GMT - finest: [f5-cloud-failover] updateAddresses: {"updateOperations":null}
Tue, 07 Apr 2020 17:54:51 GMT - info: [f5-cloud-failover] No failoverAddresses to discover
Tue, 07 Apr 2020 17:54:51 GMT - fine: [f5-cloud-failover] updateAddresses disassociate operations: undefined
Tue, 07 Apr 2020 17:54:51 GMT - fine: [f5-cloud-failover] updateAddresses associate operations: undefined
Tue, 07 Apr 2020 17:54:51 GMT - info: [f5-cloud-failover] No associations to update.
Tue, 07 Apr 2020 17:54:51 GMT - severe: [f5-cloud-failover] failover.execute() error: Cannot read property 'forEach' of undefined TypeError: Cannot read property 'forEach' of undefined
at Cloud._updateFwdRules (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:854:20)
at Cloud._updateAddresses (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:802:18)
at _discoverAddressOperations.then.operations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:181:46)
at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
Tue, 07 Apr 2020 17:54:51 GMT - finest: [f5-cloud-failover] Data will be uploaded to f5cloudfailoverstate.json: {"taskState":"FAILED","message":"Failover failed because of failover.execute() error: Cannot read property 'forEach' of undefined TypeError: Cannot read property 'forEach' of undefined\n at Cloud._updateFwdRules (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:854:20)\n at Cloud._updateAddresses (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:802:18)\n at _discoverAddressOperations.then.operations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/gcp/cloud.js:181:46)\n at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromiseCtx (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:606:10)\n at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:138:12)\n at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)\n at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)\n at runCallback (timers.js:794:20)\n at tryOnImmediate (timers.js:752:5)\n at processImmediate [as _immediateCallback] (timers.js:729:5)","timestamp":"2020-04-07T17:54:51.868Z","instance":"bigip1-dev1-sjc1-ng.c.saasdev-sed-wss-hp.internal","failoverOperations":{"addresses":null,"routes":null}}
Tue, 07 Apr 2020 17:54:51 GMT - finest: [f5-cloud-failover] Routes: {"0":{"id":"1210773612427470640","creationTimestamp":"2020-04-05T15:21:19.228-07:00","name":"route-dev1-useast1-sjc1-wanout-default","description":"f5_cloud_failover_labels={"goog-dm":"dev1-sjc1-ng"}","network":"https://www.googleapis.com/compute/v1/projects/saasdev-sed-wss-hp/global/networks/vpc-dev1-useast1-sjc1-wanout","destRange":"0.0.0.0/0","priority":900,"nextHopIp":"192.168.0.130","selfLink":"https://www.googleapis.com/compute/v1/projects/saasdev-sed-wss-hp/global/routes/route-dev1-useast1-sjc1-wanout-default","kind":"compute#route"}}
Tue, 07 Apr 2020 17:54:51 GMT - warning: [f5-cloud-failover] Next hop address to use is empty: 192.168.0.130,192.168.0.131
Tue, 07 Apr 2020 17:54:51 GMT - finest: [f5-cloud-failover] Next hop address: undefined
Tue, 07 Apr 2020 17:54:52 GMT - fine: [f5-cloud-failover] updateRoutes operations: {}
Tue, 07 Apr 2020 17:54:52 GMT - info: [f5-cloud-failover] No route operations to run
Tue, 07 Apr 2020 17:54:57 GMT - finest: socket 252 closed

**Comment by alaari-f5** [comment]
Thanks for reaching out to us with with your issue. This is a bug and I've filed a bug ticket, internal ID AUTOSDK-275, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with release 1.3.
