### ISSUE TITLE
document: missing folder in logging file location in documentation on clouddocs.f5.com

### ISSUE THREAD

**Issue by Klipope** [F5Networks/f5-cloud-failover-extension#30]
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/logging.html

says that: "Cloud Failover Extension logs to /var/log/restnoded.log" 

It should be /var/log/restnoded/restnoded.log 
at least in v15.1.0.2 in Azure and with CFE 1.3.0 - tested today.

**Comment by shyawnkarim** [comment]
Nice catch. Thanks for reporting this. We are now tracking this fix to our documentation internally with ID AUTOSDK-369.

**Comment by shyawnkarim** [comment]
Closing.

This bug was resolved with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/issues/23).
