### ISSUE TITLE
feature request: AWS route added if it does not exist?

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#31]
This is not a bug but a feature request for your consideration: A colleague was configuring CFE to update a route in AWS, and his declaration was correct. However, the route he was looking to update in the route table did not exist, and hence his failure to update this route. Once he created this route within AWS, CFE failover worked great.

He had assumed that CFE would create the route for him. While we know that the route must exist to be updated, is this a reasonable assumption a customer might make? If yes, would you consider having CFE create the route if it is not found in the tagged AWS route table? Or, perhaps, log messages to indicate that the route table was found, but the specified route does not exist? If not, please close issue, but I thought to log for your consideration.

**Comment by f5-chidambaram** [comment]
Hi, Thanks for the feedback.
Auto creating the routes may lead to other critical issues. But it is fair to indicate it clearly in the log message.
And this has been added to our backlog, internal ID AUTOSDK-376.

**Comment by f5-applebaum** [comment]
thank you for the feedback/interest. We reviewed the request and concluded that CFE should not auto CREATE cloud resources and architecturally will leave creation of cloud resources to other entities (ex. same cloud orchestrator / function who created the instances themselves, other dependencies, etc).

**Comment by shyawnkarim** [comment]
Closing. 

In [Release 1.6](in Release 1.6.), /dry-run was added, which allows you to check what resources will be updated from a failover event.
