### ISSUE TITLE
CFE attempts to connect to AWS S3 buckets in different regions

### ISSUE THREAD

**Issue by hparr** [F5Networks/f5-cloud-failover-extension#33]
When you initiate a failover with CFE it will attempt to use S3 buckets in a different region.  This leads performance issues in isolated environments and users must leverage VPC Endpoint services as these are region specific with updates taking nearly a minute.  

The correct behavior is that the system isolates the API calls to the region that it is located in.  For example a system in us-west-2 should not be calling us-west-1, ca-central, us-east-1 etc, but this can be seen in a packet capture. 

CFE Version 1.3 validated as having this incorrect behavior.

**Comment by f5-chidambaram** [comment]
Hi, thanks for reporting this. This has been added to the backlog, issue ID AUTOSDK-375.

**Comment by pdiliberto** [comment]
Same behavior on CFE 1.4

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).
