### ISSUE TITLE
Adding multiple routes to scopingAddressRanges

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-cloud-failover-extension#35]
Documentation implies that it is possible to add multiple destination routes to the declaration. E.g. the rage https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/docs/userguide/configuration.rst refers to "A list of the destination routes to update in the event of failover".

I tried to add the second value 192.0.6.0/24 to the declaration file as follows:
      "scopingAddressRanges":[
           {
             "range":"192.0.2.0\/24, 192.0.6.0\/24"
           }
       ],
but received the following error message after using "declare":
{"message":"Invalid declaration: [{\"keyword\":\"format\",\"dataPath\":\".failoverRoutes.scopingAddressRanges[0].range\",\"schemaPath\":\"#/properties/failoverRoutes/properties/scopingAddressRanges/items/properties/range/format\",\"params\":{\"format\":\"ipAddressWithCidr\"},\"message\":\"should match format \\\"ipAddressWithCidr\\\"\"}]"}500

I also tried without the separating space (i,e, "192.0.2.0\/24,192.0.6.0\/24") but received the same error message.

The document quoted above does not describe how "ranges" (under scopingAddressRanges) can become an array similar to "items" under defaultNextHopAddresses.

**Comment by nmenant** [comment]
Hi,

this is our multiple range should be defined. We work on providing an example on clouddocs

`
{

    "class": "Cloud_Failover",
    "environment": "aws",
    "externalStorage": {
      "scopingTags": {
        "f5_cloud_failover_label": "mydeployment"
      }
    },
    "failoverAddresses": {
      "enabled": true,
      "scopingTags": {
        "f5_cloud_failover_label": "mydeployment"
      }
    },
    "failoverRoutes": {
      "enabled": true,
      "scopingTags": {
        "f5_cloud_failover_label": "mydeployment"
      },
      "scopingAddressRanges": [
        {
          "range": "192.168.11.0/24",
          "nextHopAddresses": {
            "discoveryType": "static",
            "items": [
              "192.0.1.12",
              "192.0.1.13"
            ]
          }
        },
        {
          "range": "192.168.12.0/24",
          "nextHopAddresses": {
            "discoveryType": "static",
            "items": [
              "192.0.2.12",
              "192.0.2.13"
            ]
          }
        }
      ]
   }
}
`

**Comment by nmenant** [comment]
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/example-declarations.html#multiple-next-hop-addresses

The doc has been updated to provide an example of it

**Comment by f5-chidambaram** [comment]
Closing this issue.
