### ISSUE TITLE
Failover is not triggered when it should be after both F5 VMs are stopped or rebooted

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-cloud-failover-extension#36]
If both of the F5 VMs are stopped or rebooted failover of AWS objects is not triggered by the script even the new F5 VM elected active is not the same as before the reboot. Let's consider the following sequence of events that reproduces the error consistently:

1. bigip1 is Active and AWS PIPs/routes are pointing to it (bigip2 is Standby).
2. Both systems are stopped at the AWS-instance level.
3. bigip2 is started and becomes Active. Failover is not triggered and AWS keeps trying to use bigip1 which is still unavailable. The outage continues until the bigip1 is brought up as well.
4. bigip1 is started and becomes Standby. Failover is still not triggered and AWS will send traffic to bigip1. If VSs are configured in traffic-groups None the requests will be processed by bigip1, but persistence tables may not work correctly, and the discrepancy in Active/Standby state at the F5 vs AWS level will cause confusions.

I have not tested the behavior of the cluster when both VMs are "shutdown" at the F5 level (rather than stopped at the AWS level), but I suspect it will be as described above.

**Comment by f5-chidambaram** [comment]
Hi, this is a documentation limitation, and it has been added to the backlog, internal ID AUTOSDK-409.

**Comment by vvt137** [comment]
Further analysis (in AWS environment) shows that the issue is intermittent and occurs when f5-cloud-failover script is not fully initialised when the BIG-IP VE changes status from Standby to Active. 

In my tests (using https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/failover/across-net/via-api/3nic/existing-stack/payg/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template) time between the `Journal started` message in /var/log/ltm and the `[f5-cloud-failover] Global logLevel set to` message in /var/log/restnoded/restnoded.log was between 68 and 99 seconds. 

In the same set of tests the time between the `Journal started` and `Active for traffic group traffic-group-1` messages in /var/log/ltm was between 72 and 122 seconds.

Ideally, completion of the LTM HA peering establishment should be made conditional on the readiness of the CFE and there should be a configurable timeout (which would ensure that HA peering is eventually established if CEF is misconfigured, etc). 
Based on my test results, the default value of the should be around 30 seconds for AWS implementations.

Alternatively, unconditional 30-second delay may be introduced. Please advise the recommended ways to implement such a delay (e.g. by using "hidden" bigdb keys).

**Comment by nmenant** [comment]
With 1.5, we have updated CFE to be able to handle more gracefully this situation. We need to update our documentation to highlight also that: 
if reboots are performed and for some reason the objects are mapped to the wrong BIG-IP the user can force a failover event by POSTing to the /trigger endpoint of the currrently active BIG-IP (as described here: https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/apidocs.html#tag/Trigger) which should have the cloud objects

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).
