### ISSUE TITLE
Implications of not being able to tag individual routes in AWS

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-cloud-failover-extension#37]
The "Tag the User-Defined routes in AWS" section in
https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/docs/userguide/aws.rst
implies that a route (or routes) in AWS can be tagged individually:
"... you need to tag the route(s) in a route table with a key-value pair that will correspond to the key-value pair in the failoverRoutes.scopingTags section of the CFE declaration".

It turns out, in AWS only a route table object can be assigned tags and individual routes cannot.

We also need to take into account that in AWS "...each tag key must be unique, and each tag key can have only one value" (see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html).
As a result, to support implementation of multiple F5 HA clusters within the same VPC, the value assigned to the route table for the key "f5_cloud_failover_label" should not be f5-cluster-specific. In other words, this key/value pair should be considered a switch to enable/disable the CFE-based failover of routes for any HA clusters of F5s within the VPC (e.g. the recommended key:value should be "f5_cloud_failover_label:enabled" rather that, say "f5_cloud_failover_label:bigip_cluster1").

In my opinion this is an important consideration in the context of tagging-strategy part of CFE-based failover implementations and should be documented.

**Comment by f5-chidambaram** [comment]
Thanks for the feedback. This has been added to the backlog, internal tracking ID AUTOSDK-399.

**Comment by nmenant** [comment]
@f5-chidambaram - doc has been updated accordingly. Please close

**Comment by shyawnkarim** [comment]
Closing.

The documentation was updated in [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).
