### ISSUE TITLE
RPM not available after BIG-IP upgrade

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-cloud-failover-extension#38]
The cloud failover extension disaappears after you upgrade the BIG-IP.

## Workaround
You must re-install the cloud failover RPM in order for the failover to work properly. The failover declaration JSON is still intact. However, without the RPM/extension installed then you will receive a 404 error due to endpoint missing.

**Comment by f5-chidambaram** [comment]
Thanks for reporting this. This has been added to the backlog, internal ID AUTOSDK-398.

**Comment by f5-chidambaram** [comment]
This is a duplicate of https://github.com/F5Networks/f5-cloud-failover-extension/issues/48. 
Internal tracking ID AUTOSDK-448. 
Closing this now.
