### ISSUE TITLE
CFE v 1.4.0 swapping public to private IP mappings in Azure VE BIG-IP v15.1.0.4 

### ISSUE THREAD

**Issue by prestonhashworth** [F5Networks/f5-cloud-failover-extension#39]
After forcing offline to initiate failover, CFE 1.4.0 successfully moves IPs to the secondary member big-ip but in Azure the mappings of public IPs are changed (in this case swapped between two VS), essentially a failure of failover as it breaks the web app.

**Comment by mikeoleary** [comment]
To add to this issue, I have now reproduced in a standalone demo environment and I would call this "failover of multiple public IP addresses in Azure not working"

## Issue description
Using CFE (multiple versions) in Azure I have reproduced this issue. Private IP's are moved between external NIC's but the public IP's are swapped between private IP's. I,e, the Public:Private mapping is not preserved correctly.

## Steps to reproduce
1. Deploy F5's supported Azure template for [HA pair failover via API]. (https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg). This ships with CFE 1.3 and configures CFE for us.
2. Set up 2x VIP's with public IP addresses. 
3. Perform failover. I have witnessed the private IP's migrated between devices, but the public IP's associated are swapped between the 2 private IP's. 

## Example
My VIPs and their associated IPs from my last test.

BEFORE FAILOVER
10.0.1.5 | 52.184.243.219
10.0.1.6 | 52.184.243.221

AFTER FAILOVER
10.0.1.5 | 52.184.243.221
10.0.1.6 | 52.184.243.219

## Troubleshooting done
- I have tested failover with CFE 1.3 and 1.4
- I have not tested with more than 2 VIP's.
- Interestingly, the mapping swaps back upon failback. I.e, Failover in 1 direction causes a reversal of the public:private mapping, and failover in the other direction reverses that mapping again.
- So, if you fix this problem after failover by manually swapping your Public IP associations, they will still be swapped at the next failover event.

**Comment by f5-chidambaram** [comment]
Thanks for reporting this. This issue has been added to the backlog, internal ID AUTOSDK-404.

**Comment by mikeoleary** [comment]
In case others read this issue, the workaround here was to ensure that any secondary ipconfigs in Azure that are mapped to VIP's on F5 were set to "Static" and not "Dynamic". This can be updated in GUI or CLI while machine is running without issue.

CFE will work as expected when ipconfigs are static and the strong recommendation is to use static, not dynamic ipconfigs when using CFE.

**Comment by nmenant** [comment]
@f5-chidambaram 

We have taken the following actions:
- CFE doc has been updated to highlight the need to use STATIC IP
![image](https://user-images.githubusercontent.com/13098758/93745498-f12b6880-fbf3-11ea-8438-61a2e94f895f.png)
- The Cloud template team works on updating our templates to deploy secondary ip as static and not dynamic

Please Close

**Comment by prestonhashworth** [comment]
Thank you so much Team!
