### ISSUE TITLE
Routes failover with CFE needs the FailoverAddresses set to True even if only routes need to be updated

### ISSUE THREAD

**Issue by Klipope** [F5Networks/f5-cloud-failover-extension#40]
This was tested in Azure and in AWS. It was tested with Static and dynamic declarations for routes (routeTag). 
For the routes failover to happen (i.e. route update) with CFE it requires : 
"failoverAddresses": {		
set to 
		"enabled": true,

If only "failoverRoutes" is set to True and "failoverAddresses" is set to false, the routes will not be updated. 
the logs show the following message: 
info: [f5-cloud-failover] No route operations to run

as soon as the "failoverAddresses" is set to True (of course with no secondary IPs or PIP to move over) the routes are updated. no other setting is changed in the declaration. 

Can you explain why this setting is needed and if this is mandatory, could you update the documentation accordingly. 
Thanks

**Comment by nmenant** [comment]
Hi,

Thanks for sharing this. AUTOSDK-412 has been created to review this

**Comment by nmenant** [comment]
fixed with 1.5. 

Please close @f5-chidambaram

**Comment by SalimHaddou** [comment]
Tested in 1.5.0 in Azure. I confirm it works with "failoverRoutes" set to true and "failoverAddresses" set to false. @f5-chidambaram @nmenant

**Comment by nmenant** [comment]
Thanks for the update! Closing the issue
