### ISSUE TITLE
intended use of f5_cloud_failover_nic_map tags is not documented

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-cloud-failover-extension#46]
The CFE clouddocs state that the f5_cloud_failover_nic_map tags are required:

> NIC mapping tag: the name is static but the value is user-provided (f5_cloud_failover_nic_map:) and must match the 
> corresponding NIC on the secondary BIG-IP. The example below uses f5_cloud_failover_nic_map:external. 
> This name/value tag will correspond to the name/value tag you use in the failoverAddresses.scopingTags section of 
> the CFE declaration.

However, their purpose and intended use of these tags is not documented. Furthermore, the current version (v5.7.0) of the AWS CFTs do not set these tags and API-based failover seems to operate successfully without them.

Note that the Azure templates do set these additional tags, see https://github.com/F5Networks/f5-azure-arm-templates/issues/172#issuecomment-610376552

**Comment by f5-chidambaram** [comment]
Hi, 

This part has been removed from the CFE documentation and was released on clouddocs with CFE 1.2
> This name/value tag will correspond to the name/value tag you use in the failoverAddresses.scopingTags section of
> the CFE declaration.

We will document the intended scenario/use of f5_cloud_failover_nic_map. We are tracking it with internal ID AUTOSDK-439

**Comment by nmenant** [comment]
@f5-chidambaram 

Our documentation has been updated: 
![image](https://user-images.githubusercontent.com/13098758/93742992-71030400-fbef-11ea-9041-7f40f8369a6f.png)

![image](https://user-images.githubusercontent.com/13098758/93743042-8b3ce200-fbef-11ea-9512-14ff658a7c9c.png)

**Comment by nmenant** [comment]
documentation has been updated accordingly
