### ISSUE TITLE
IPv6 support needed for failover of EIP's in AWS

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#49]
## Summary
We need support for failover of IPv6 addresses in AWS. According to [faq in current documentation](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/faq.html#faq-support-ipv6) that is not supported yet.

## Detail 
We have both IPv4 and IPv6 addresses today on-prem on our F5 devices, and are required to migrate the application and F5 services to AWS. We have a requirement to continue to support both IPv4 and IPv6 in AWS, and we would like to use CFE for high availability because we need fast failover times to meet our strict uptime SLA. We have compliance enforced by a 3rd party so changing these requirements may be complex. 

With an internet-facing deployment of F5 VE in AWS that supports IPv6 VIPs, we need the CFE to support failover of these VIPs. Can you suggest any workaround or timelines so we can plan for this? Many thanks.

**Comment by f5-chidambaram** [comment]
Hi Mike, we are tracking this new feature request with internal ID AUTOSDK-445. Thanks!

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.7](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.7.0).
