### ISSUE TITLE
documentation azure - manual installation procedure - gateway for metadata service

### ISSUE THREAD

**Issue by Klipope** [F5Networks/f5-cloud-failover-extension#52]
## Description
I would like to get confirmation on the following steps in Azure manual procedure for CFE installation. 
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#using-tmsh

the documentation says: 
"to configure the route on BIG-IP to talk to Azure’s Instance Metadata Services, use either of the following commands:"
it does not say one has to adapt the gateway listed in the TMSH command to his own environment. 
the gateway in the documentation is 192.0.2.1 
is this change required or not? or does one have to copy the tmsh command as it is? 

I tried twice this configuration and even though my templates had the DCHP routes I had to add that specific route for the metadata service. using it with the gateway mentioned in the documentation - strictly following the documentation - gave me the ECONNREFUSED error in restnoded.log (which is by the way not easily readable: does it mean the service was reached but connection was refused or that the service was not reached?) changing the gateway to my own vnet appropriate gateway did the trick. 

please confirm and update the documentation accordingly if needed. 

Thanks 
best regards

**Comment by nmenant** [comment]
Hi,

Yes you need to change 192.0.2.1 to specify your management network's default gateway. We are already working on updating the documentation to make it more obvious. 

Please review: https://github.com/F5Networks/f5-cloud-failover-extension/issues/51

**Comment by shyawnkarim** [comment]
Closing.

Updates to our Azure Quickstart guide were included with [Release 1.6](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.6.0).
