### ISSUE TITLE
existing documentation does not mention CFE

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-cloud-failover-extension#53]
The page at: https://clouddocs.f5.com/cloud/public/v1/aws/AWS_ha.html

Has no mention of CFE and it is confusing.

**Comment by shyawnkarim** [comment]
The docs on that page are referring to the old method of failover, which is why they don't mention CFE. We know they need updating and plan to do so.

**Comment by shyawnkarim** [comment]
Closing. Information on CFE has been added to that page.
