### ISSUE TITLE
CFE giving back 400 on /inspect and /reset - Azure

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-cloud-failover-extension#54]
## Description
15.1.0.4 and CFE 1.5 - both /inspect and /reset are handing back 400 errors. Other API endpoints are working as expected, **it is the same on both units (active/standby)**

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.5
- BIG-IP version: 15.1.0.4
- Cloud provider: Azure
- Azure Region: North Central

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interruptions in system operations.
 5. **Severity 5 (Trivial)** : Defect is not causing any interruptions to system operations, but none-the-less is a bug.

## Testing
Units have access to metadata and they can query it, so the MSI is working as expected. All tags have been in place and verified using: ```curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2020-06-01"```

In var/log/restnoded we can see the CFE update come in but there is never an event for /inspect or /reset

![restnoded](https://user-images.githubusercontent.com/20847865/96025234-b343ed80-0e09-11eb-9f0f-be0e300ea8bc.png)

Example of CFE:
```
{
    "class": "Cloud_Failover",
    "environment": "azure",
    "externalStorage": {
        "scopingTags": {
            "f5_cloud_failover_label": "resource_group_name"
        }
    },
    "failoverAddresses": {
        "enabled": true,
        "scopingTags": {
            "f5_cloud_failover_label": "resource_group_name"
        }
    },
    "failoverRoutes": {
        "enabled": true,
        "scopingTags": {
            "f5_cloud_failover_label": "resource_group_name"
        },
        "scopingAddressRanges": [
            {
                "range": "192.0.2.0/24"
            }
        ],
        "defaultNextHopAddresses": {
            "discoveryType": "static",
            "items": [
                "192.0.2.10",
                "192.0.2.11"
            ]
        }
    },
    "schemaVersion": "1.5.0"
}
```

Restjavad logs look like they are throwing exceptions:

![restjavadwhole](https://user-images.githubusercontent.com/20847865/96027133-4d0c9a00-0e0c-11eb-8b36-bc8e21668eaa.png)

**Comment by jmcalalang** [comment]
This issue is 100% reproducible with removing access to the internet from the "external" interface. In this case it appears that Private Endpoint/Link is needed to access the storage account.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I have added your suggestion to our backlog and we are tracking it internally with ID AUTOSDK-517.

**Comment by shyawnkarim** [comment]
Closing. Documentation on private endpoints can be seen here:

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/isolated-env.html
