### ISSUE TITLE
Question about proxy on v1.6 (AWS)

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-cloud-failover-extension#55]
## Do you already have an issue opened with F5 support?
No

## Description
Question about Proxy support in v1.6 on AWS: the documentation states that all API calls will be made through the proxy, if configured.  What about the S3 bucket access? We have a VPC Endpoint configured for S3 and I'm because the BIGIP proxy settings do not support "no proxy" setting for configured destinations, I would need to know if S3 access will use the proxy too.

## Environment information

- Cloud Failover Extension Version: 1.6
- BIG-IP version: 14.1.2.8
- Cloud provider: AWS

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by shyawnkarim** [comment]
S3 access will also be by proxy.

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you have any more questions.
