### ISSUE TITLE
AWS API Failover 'update address operations' failing

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-cloud-failover-extension#56]
## Description

Note: we have worked-around this problem by downgrading to CFE v1.4.  The same configuration works with v1.4, but not with v1.6.1.

We’ve been working with a customer to troubleshoot a problem where CFE failover (single EIP only) is not working after they had deployed into AWS using the [failover across-net](https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/payg) CFT.  Having checked through their configuration (AWS primary/secondary IPs, BIG-IP self-IPs/VIPs, tags, S3, IAM, CFE declaration) and corrected a couple of mistakes, it’s still not working.
 
During failover the EIP is dissociated from the ENI, as expected, but the strange thing is that the ‘current’ secondary IP is also removed from its ENI.  The logs show the correct addresses are identified, initially:
 
`Fri, 04 Dec 2020 16:16:33 GMT - finest: [f5-cloud-failover] Moving public address: 54.72.135.176 to address: 10.0.11.154, and off of 10.0.1.179`
 
But then it seems to go wrong:
 
```
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Address discovery: {
     "publicAddresses": {
           "54.72.135.176": {
                "current": {
                     "PrivateIpAddress": "10.0.1.179",
                     "AssociationId": "eipassoc-028c34ecac37dcf70"
                },
                "target": {
                     "PrivateIpAddress": "10.0.11.154",
                     "NetworkInterfaceId": "eni-086be960003ee090c"
                },
                "AllocationId": "eipalloc-0f7100836c8730a2c"
           }
     },
     "interfaces": {
           "disassociate": [{
                "networkInterfaceId": "eni-02767a14c69fe1318",
                "addresses": [{
                     "address": "10.0.1.179",
                     "publicAddress": "54.72.135.176"
                }]
           }],
           "associate": [{
                "networkInterfaceId": "eni-086be960003ee090c",
                "addresses": [{
                     "address": "10.0.1.179",
                     "publicAddress": "54.72.135.176"
                }]
           }]
     },
     "loadBalancerAddresses": {}
}
```
 
 
The logs then suggest that CFE is trying to move the secondary IP and the EIP to the target ENI (which is in a different AZ, hence the subnet address range errors):
 
```
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Update address operations to perform {"publicAddresses":{"54.72.135.176":{"current":{"PrivateIpAddress":"10.0.1.179","AssociationId":"eipassoc-028c34ecac37dcf70"},"target":{"PrivateIpAddress":"10.0.11.154","NetworkInterfaceId":"eni-086be960003ee090c"},"AllocationId":"eipalloc-0f7100836c8730a2c"}},"interfaces":{"disassociate":[{"networkInterfaceId":"eni-02767a14c69fe1318","addresses":[{"address":"10.0.1.179","publicAddress":"54.72.135.176"}]}],"associate":[{"networkInterfaceId":"eni-086be960003ee090c","addresses":[{"address":"10.0.1.179","publicAddress":"54.72.135.176"}]}]},"loadBalancerAddresses":{}}
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Starting disassociating Elastic IP {}
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Disassociating address using eipassoc-028c34ecac37dcf70
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Starting reassociating addresses using operations {"disassociate":[{"networkInterfaceId":"eni-02767a14c69fe1318","addresses":[{"address":"10.0.1.179","publicAddress":"54.72.135.176"}]}],"associate":[{"networkInterfaceId":"eni-086be960003ee090c","addresses":[{"address":"10.0.1.179","publicAddress":"54.72.135.176"}]}]}
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Disassociating [{"address":"10.0.1.179","publicAddress":"54.72.135.176"}] from eni-02767a14c69fe1318
Fri, 04 Dec 2020 16:16:33 GMT - fine: [f5-cloud-failover] Associating [{"address":"10.0.1.179","publicAddress":"54.72.135.176"}] to eni-086be960003ee090c
Fri, 04 Dec 2020 16:16:33 GMT - finest: [f5-cloud-failover] Function error, retrying: The association ID 'eipassoc-028c34ecac37dcf70' does not exist Retries left: 50
Fri, 04 Dec 2020 16:16:33 GMT - finest: [f5-cloud-failover] Function error, retrying: Address does not fall within the subnet's address range Retries left: 50

``` 
Is this a bug?

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.6.1
- BIG-IP version: 15.1
- Cloud provider: AWS

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with AUTOSDK-501.

**Comment by nmenant** [comment]
Update: please ensure your customer is assigning their virtual server address to the traffic-group "none". Based on engineering, this is when such a mistake is done that CFE is not working as expected. 

Could you confirm if your customer leverages traffic-group "none" for his Virtual Server Address ?

**Comment by shyawnkarim** [comment]
Closing.

Please reopen if you are still having issues.
