### ISSUE TITLE
DCHP default route does not catch Azure metadata 169.254.169.254 traffic: ECONNREFUSED

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#6]
(Issue moved from https://github.com/f5devcentral/f5-cloud-failover-extension/issues/21)
Reported By:  @JeffGiroux

A default route created by Azure DHCP does not catch traffic going to Azure metadata service as required by the CFE pre-reqs which is 169.254.169.254. If I hit certain API URLs for CFE then I get ECONNREFUSED.

Example endpoint = /reset
Hitting above endpoint without 169.254.169.254 specifically configured as a route will result in unreachable.

My Azure deployment creates DHCP routes like this...

sys management-route default {
description configured-by-dhcp
gateway 10.90.1.1
network default
}
sys management-route dhclient_route1 {
description configured-by-dhcp
gateway 10.90.1.1
network 168.63.129.16/32
}

The note in documentation states this...
"Certain BIG-IP versions and/or topologies may use DHCP to create the management routes (for example: dhclient_route1), if that is the case the below steps are not required."

However, my dhclient_route1 does not contain the network address required by CFE. Therefore, I have to manually add an additional route according to CFE documentation. My example...

tmsh modify sys db config.allow.rfc3927 value enable
tmsh create sys management-route metadata-route network 169.254.169.254/32 gateway 10.90.1.1

If you do not add the config.allow.rfc3927 ahead of time, then F5 will not allow you to add the 169.x.x.x route. Error = 01020062:3: IP Address 169.254.169.254 is invalid, link-local address not allowed.

Can you validate and/or update documentation if needed.

**Comment by alaari-f5** [comment]
Internal bug ID AUTOSDK-236 created for this.

**Comment by shyawnkarim** [comment]
Closing. This was fixed with Release 1.2.
