### ISSUE TITLE
CFE fails in AWS if unused IPv6 address is listed in Virtual Addresses

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#75]
## Do you already have an issue opened with F5 support?
No

## Description
The following scenario causes CFE to fail:
- IPv6 VS is created, but is then deleted or the IP address is changed
- The IPv6 address remains in the list of Virtual Addresses, even though there is no corresponding Virtual Server for this address
- IPv6 address is not, or no longer, configured in AWS on ENI.

Error message I receive after deleting an IPv6 address from an ENI and deleting the F5 VS, and then attempting failover: (restnoded.log)

Wed, 23 Jun 2021 20:27:40 GMT - fine: [f5-cloud-failover] disassociating ipv6 addresses: {"NetworkInterfaceId":"eni-xxxxxxxxxxxxx","Ipv6Addresses":["xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx","xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx","xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx"]}
Wed, 23 Jun 2021 20:27:40 GMT - finest: [f5-cloud-failover] Function error, retrying: The address 'xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx' is not mapped to interface ID 'eni-xxxxxxxxxxxxx' Retries left: 0
 
## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: CFE v1.8
- BIG-IP version: v16.0.1.1
- Cloud provider: AWS

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
This issue is being tracked internally with ID AUTOSDK-557.

**Comment by mikeoleary** [comment]
After testing with Nitin, I can confirm the following steps will reproduce this error:

1) Create VS with IPv6 address and hit save.
2) **Edit** the Destination IP address of this new VS. (Perhaps you made a typo when you first created the VS, and now you want to fix it). Do not delete and recreate with a new destination IP, rather, edit the VS you created in step 1.
3) Now, notice that both the original IPv6 address, **and** the updated IPv6 address are listed under "Virtual Addresses". So we have an IPv6 address listed under Virtual Addresses for which there is no Virtual Server.
4) Ensure that the current destination IP address is configured in AWS, but that the previous IP address is not configured in AWS.
5) Perform failover. Logs show a function error because we are trying to move an IP address that does not exist.

**Comment by shyawnkarim** [comment]
Closing.

This issue was addressed with [Release 1.10](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.10.0).
