### ISSUE TITLE
IPv6 addresses in AWS are only failed over if IPv4 addresses exist too

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#76]
## Do you already have an issue opened with F5 support?
No.

## Description
CFE failover is working when I have IPv4 and IPv6 VIPs and they are both in Traffic Group 1. However CFE fails if:
a) I have no IPv4 addresses, only IPv6 VIPs, or
b) If my IPv4 addresses are in traffic group None and my IPv6 address is in Traffic Group 1. 

CFE appears to ignore the IPv6 addresses unless it finds IPv4 addresses to move also. 

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.8
- BIG-IP version: 16.0.1.1
- Cloud provider: AWS

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

**Comment by shyawnkarim** [comment]
This issue is being tracked internally with ID AUTOSDK-558.

**Comment by shyawnkarim** [comment]
Closing.

This issue was addressed with [Release 1.10](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.10.0).
