### ISSUE TITLE
CFE fails to find IP addresses to move in Traffic Group None

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-cloud-failover-extension#77]
## Do you already have an issue opened with F5 support?
No

## Description
If my VIPs are in Traffic Group None, they are ignored and not moved as part of CFE failover. Logs show that there are no IP addresses to move.

I believe prior to CFE v1.8, and after about v1.5, VIPs were _required_ to be placed in Traffic Group None. Today the [documentation](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/faq.html#faq-tg-none) still states so, and I believe this needs updating.

The requirement of TG None was confusing for customers and this was removed in 1.8 I believe, so now I can have my VIPs in the default traffic-group-1 and they are failing over nicely. However there are 2 reasons I still want VIP's in TG None to failover between ENI's:
a) some customers will have configs where VIP's are in TG None due to requirements of CFE prior to 1.8. Upgrading to CFE 1.8 will break their failover experience.
b) there are may still be scenarios where I want to have a VIP in TG None but also want it to fail over between devices in AWS. 

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: v1.8
- BIG-IP version: 16.0.1.1
- Cloud provider: AWS 

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by shyawnkarim** [comment]
This issue is being tracked internally with ID AUTOSDK-505.

**Comment by shyawnkarim** [comment]
Closing.

This issue was addressed with [Release 1.10](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.10.0).
