### ISSUE TITLE
GCP: On Failover CFE updates forwarding rules based on IP only

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#8]
(Issue moved from: https://github.com/f5devcentral/f5-cloud-failover-extension/issues/18)
Reported By: @abhishek-batapati 

Issue:
On failover- CFE updates forwarding rules based on IP only. We have a scenario where same IP is used in forwarding rules target to 2 sets of F5s but on different port numbers.

Scenario:
2 set of F5 using same IP with one set using ports 80 & 443 and other set using ports 8080 & 8443

Forwarding rules are defined with IP + Port as mentioned above.

f5-cluster-1-tcp-443 us-west1 35.xx.xx.108 TCP us-west1-a/targetInstances/bigip1-cluster1-ti
f5-cluster-1-tcp-80 us-west1 35.xx.xx.108 TCP us-west1-a/targetInstances/bigip1-cluster1-ti
f5-cluster-2-tcp-8080 us-west1 35.xx.xx.108 TCP us-west1-b/targetInstances/bigip1-cluster2-ti
f5-cluster-2-tcp-8443 us-west1 35.xx.xx.108 TCP us-west1-b/targetInstances/bigip1-cluster2-ti

Virtual servers are defined in both cluster listening on IP+Port as defined above.

On triggering a failover on cluster-1, F5 in cluster-1 made changes to all 4 forwarding rules described above.

Requirement:
We have a requirement where F5 CFE should look into IP+Port instead of IP only to make changes on the forwarding rules.

**Comment by alaari-f5** [comment]
Thank you for reaching out to us with this feedback. I've created internal issue AUTOSDK-203 for this and have added it to our backlog.

**Comment by shyawnkarim** [comment]
Closing. 

This enhancement was included with Release 1.6.
