### ISSUE TITLE
Request to have CFE support alien IP range failover in AWS

### ISSUE THREAD

**Issue by jfowlerf5** [F5Networks/f5-cloud-failover-extension#81]
## Do you already have an issue opened with F5 support?

     There is not currently an f5 support case opened for this issue.

## Description

      Working with integrating BIG-IP CFE into an AWS environment to minimize management of the secondary IP addresses on the EC2 instances.   The stakeholders would prefer to utilize alien IP range in the environment.  

      Searched for documentation to determine if CFE supports alien IP range - I have been unable to find documentation to support this.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 
      N/A
- BIG-IP version: 
      15.1.2
- Cloud provider: 
      AWS

## Severity Level
Not a bug - feature request.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trivial)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this enhancement internally with ID AUTOSDK-559.

**Comment by mikeoleary** [comment]
@jfowlerf5 are you asking for documentation, or if updating "alien ranges" works with CFE? Yes, you can update aws routes with CFE, and doing this with alien ranges is something I often prefer for the same reason you mention: minimizing management of the secondary IP addresses. Reach out internally within F5 if you'd like to know more.

**Comment by f5-applebaum** [comment]
Alien Routes leverages/implements just the Route Failover functionality of CFE:

From:
https://docs.aws.amazon.com/prescriptive-guidance/latest/migration-f5-big-ip/high-density-deployments.html

"An F5 BIG-IP deployment with a Cloud Failover Extension to manage the routes"
