### ISSUE TITLE
Need Azure to support storage buckets located outside of resource group

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-cloud-failover-extension#84]
## Do you already have an issue opened with F5 support?
No

## Description
User has requirement to stand up two different resource groups. One RG is the VNet (giroux_rg) in Azure and subnets along with storage buckets. The other RG is for BIG-IP virtual machines and the objects created for the BIG-IP (giroux_bigip_rg) like NIC, public IP, disk, etc.

When I POST my CFE declaration to the BIG-IP, I receive an error when the resource groups are different (aka BIG-IP in different RG than bucket). I need to be able to rely on key:value tags and have the CFE search within the entire subscription. I have already given my system ID Contributor scope subscription to the BIG-IP. However, error in restnode configs big-ip cannot find the bucket.

```
Mon, 16 Aug 2021 15:37:44 GMT - finest: [f5-cloud-failover] Function error, retrying: The Resource 'Microsoft.Storage/storageAccounts/giroux15mystorage' under resource group 'giroux15_bigip_rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix Retries left: 2
```

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.9.0
- BIG-IP version: 15.1.2.1
- Cloud provider: Azure

## Severity Level
3

Does CFE support the ability to find storage buckets outside of the BIG-IP resource group?

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue. I've created a ticket for this RFE, internal ID AUTOSDK-562, and have added it to the backlog.

**Comment by shyawnkarim** [comment]
Closing. This issue has been resolved.

**Comment by mikeoleary** [comment]
Hi @shyawnkarim ,

I see this issue was closed but I don't see the resolution? I have a customer who also wants the StorageAccount in Azure to be in a different Resource Group than the F5 VM's, just like other resources can be in different RG's.

What is the plan for this feature request? 

Mike.
