### ISSUE TITLE
option to not move private IPs in AWS

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-cloud-failover-extension#85]
## Description
Customer observed an issue where they had deployed the across-az CFT template and deployed secondary IPs to the ENIs. When the BIG-IP system was rebooted they observe that the secondary IPs are removed by CFE.

To avoid this issue the customer had to manually disable CFE.  Ideally there should be an option for CFE to not disassociate private IPs.  This is somewhat similar to https://github.com/F5Networks/f5-cloud-failover-extension/issues/64

In this instance the customer did not need CFE for their requirements (they were using DNS to point to the private IPs in each AZ), but ideally this could be a configurable option to disable removing private IPs unless a customer is working with a same-az deployment.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.8.0
- BIG-IP version: 14.1
- Cloud provider: AWS

## Severity Level
Severity: 3

**Comment by shyawnkarim** [comment]
The fix for issue 64 will be included with the next CFE release. This new request is now being tracked internally with ID AUTOSDK-572.

**Comment by shyawnkarim** [comment]
Closing.

The CFE explicit config solves this issue. [Documentation on how to use the explicit config can be found here](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/configuration.html).
