### ISSUE TITLE
CFE failoverAddresses can't fail-over beyond one defined VS

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-cloud-failover-extension#89]
## Do you already have an issue opened with F5 support?
C3704575 is filled for this issue and qkview files are uploaded together with cfe failover logging and the cfe declaration.

## Description
When cloud failover is used with failover addresses defined in the CFE declaration, only one VS is failing over, all other defined VSes stay at the original BIG-IP and will not failover to the standby BIG-IP when a failover occurs.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.9.0
- BIG-IP version: 14.1.4.4
- Cloud provider: Azure

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

The use of Failover Addresses is a defined and supported way to deploy CFE. This function has been used in a customer engagement and the SR and this issue is filled because of that.

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue here. Its being tracked internally with ID AUTOSDK-570.

**Comment by shyawnkarim** [comment]
Closing. This issue was addressed shortly after it was filed but never closed out.
