### ISSUE TITLE
AWS - Support for Prefix assignment on ENIs

### ISSUE THREAD

**Issue by fchmainy** [F5Networks/f5-cloud-failover-extension#93]
## Do you already have an issue opened with F5 support?
No.

## Description
Most of the time, if I want to have multiple IP addresses (for NICs and VIPs) I need to choose a bigger EC2 instance type which impact the EC2 cost. AWS recently introduced IP prefix assignment on ENIs in order to overcome the limitation of IP addresses on small instance sizes.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html

For example, if I have a C5.4xLarge EC2 instance I get 30 x /28 prefixes per interfaces.

Is there a way CFE can support AWS prefix assignment?

**Comment by shyawnkarim** [comment]
Thanks for taking the time to submit this request. We are now tracking this internally with ID ESECLDTPLT-3075.

**Comment by shyawnkarim** [comment]
Closing.

@fchmainy is this still an issue you would like to see resolved? CFE is in maintenance mode and new features are no longer being added.
