### ISSUE TITLE
Support failover of 2nd traffic group

### ISSUE THREAD

**Issue by sbumpas** [F5Networks/f5-cloud-failover-extension#95]
## Do you already have an issue opened with F5 support?
No; this is an enhancement request

## Description
Specifically re: Azure CFE, we'd like ability to auto-failover 2nd traffic group.  It's my understanding only 1 traffic group is currently supported.

**Comment by shyawnkarim** [comment]
Thanks for submitting this request. CFE is currently in sustaining mode and not actively adding new functionality, however, I've added this request to our backlog for review. Internal ID, AUTOSDK-578.

**Comment by shyawnkarim** [comment]
In order for us to understand your issue better and help us prioritize it, can you reach out to me via email, s.karim@f5.com, and explain the situation you are facing and impact to you if this is not fixed.

**Comment by shyawnkarim** [comment]
Closing.

Our team reviewed your request and decided not to implement this enhancement. Cloud Failover Extension is now in maintenance mode, which means only critical bugs, CVEs, and security updates will be taken into consideration for updating CFE.

Thanks for submitting your request.
