### ISSUE TITLE
Unable to move LAN Secondary IP in Azure

### ISSUE THREAD

**Issue by auto2mate** [F5Networks/f5-cloud-failover-extension#96]
## Description
Unable to failover/move external and internal secondary IP at the same time.

External Interface (tag: external) Secondary IP is getting moved correctly but the Internal Interface Secondary IP doesn't move. I did put tag on internal interface(tag: internal) but don't know how to declare lan secondary IP

I am doing SNAT Automap on the VIP and LB has route to nodes via internal interface. By default LB is not using the LAN self IP and route the traffic to nodes, it tries to use the floating ip (mapping to external nic) so I had to create SNAT pool using LAN interface IP. Now whenever failover happens I have to update the SNAT pool with active LB LAN IP.

I am trying to find how to declare the lan secondary IP with tag as internal and swing it if failover happens, just like it does for VIP/external ip.

## Environment information
- Cloud Failover Extension Version: 1.10.0
- BIG-IP version: 17.0.0.0
- Cloud provider: Azure

Severity: 2

**Comment by auto2mate** [comment]
Any help on this issue?

**Comment by shyawnkarim** [comment]
Are you using the original discovery or explicit method. Have you tried defining both the external and internal addresses you would like to failover. Ex.

https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/examples/declarations/azure-1.7.0.json#L13-L21

Otherwise, if you're using the original discovery method, you need to have a floating address (Ex. virtual address, floating self-IP, or snat pool address) configured on the BIG-IP that matches those secondary addresses. Sounds like you may have a snat pool address configured that matches that secondary address and that should be sufficient. Recommend opening a case so we can examine your configuration/behavior more closely.

**Comment by auto2mate** [comment]
Thanks Shyawn.

 I have attempted to use the scopingTags  for internal and external both but it was swinging either internal or external but not both. so I had to remove the internal.

Yes, I do have secondary IP configure as floating IP for internal connection and using it as SNAT and trying to figure out how to swing that internal nic secondary ip during the failover.  I don't see issues in swinging external IP though.

I did have open the case with f5 tech support but they says its design issue and not supported by them.

Here is the script currently I am using with only external scoping tag - 

{  
    "class":"Cloud_Failover",  
    "environment":"azure",  
    "controls":{  
        "class":"Controls",  
        "logLevel":"silly"  
    },  

    "externalStorage":{  
    "scopingName": "xxxxxxxxxxxxx"  

    },  
    "failoverAddresses":{  
        "enabled":true,  
        "scopingTags": {  
            "f5_cloud_failover_nic_map": "external"  
        },  

    "addressGroupDefinitions": [  
        {  
            "type": "networkInterfaceAddress",  
            "scopingAddress": "10.10.10.134"  
        }, 
        { 
            "type": "networkInterfaceAddress", 
            "scopingAddress": "10.10.10.135" 
        }, 
        { 
            "type": "networkInterfaceAddress", 
            "scopingAddress": "10.10.20.136" 
        } 

    ]  

    }  
}

**Comment by auto2mate** [comment]
Any help on this?

**Comment by f5-applebaum** [comment]
Failing Over Secondary IPs is supported. 

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#azure-failover-event-diagram

Sorry you were told this was not the case. 

I noticed the config above is off.  

Discovery via Tags:
```
{
  "schemaVersion": "1.0.0",
  "class": "Cloud_Failover",
  "environment": "azure",
  "controls": {
    "class": "Controls",
    "logLevel": "silly"
  },
  "externalStorage": {
    "scopingTags": {
      "f5_cloud_failover_label": "test7777"
    }
  },
  "failoverAddresses": {
    "enabled": true,
    "scopingTags": {
      "f5_cloud_failover_label": "test7777"
    },
    "requireScopingTags": false
  }
}
```


or Static Config:
```
{
  "schemaVersion": "1.0.0",
  "class": "Cloud_Failover",
  "environment": "azure",
  "controls": {
    "class": "Controls",
    "logLevel": "silly"
  },
  "externalStorage": {
    "scopingTags": {
      "f5_cloud_failover_label": "test7777"
    }
  },
  "failoverAddresses": {
    "enabled": true,
    "addressGroupDefinitions": [
      {
        "type": "networkInterfaceAddress",
        "scopingAddress": "10.0.1.101"
      },
      {
        "type": "networkInterfaceAddress",
        "scopingAddress": "10.0.2.10"
      },
      {
        "type": "networkInterfaceAddress",
        "scopingAddress": "10.0.2.20"
      }
    ]
  }  
}
```
I quickly validated with a 
floating Self IP
snatpool address

and secondaries were re-mapped with first Discovery via Tags config but either way, NICs should be tagged separately.

ex. 
External NICs:
cloud_failover_label: test7777
cloud_failover_nic_map: external

Internal NICs:
cloud_failover_label: test7777
cloud_failover_nic_map: internal


Please open a case. Will need to see full config + logs to see.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if you would like additional support.
