### ISSUE TITLE
F5 Azure CFE Storage via private ip How to

### ISSUE THREAD

**Issue by jz01010101** [F5Networks/f5-cloud-failover-extension#97]
## Do you already have an issue opened with F5 support?
raised request with F5 they suggest checking here as well.

## Description
I'm trying to setup my big-ip in azure to talk to the private storage not public (we are isolated by security requirements), i cannot find documentation to set the custom ip/dns name How do i set the CFE code to utilize a custom ip/dns to talk to my storage private ip in Azure so i can finalize CFE setup.

default action below is to talk to extip 

finest: [f5-cloud-failover] Listing Storage Accounts
finest: [f5-cloud-failover] Function error, retrying: connect ECONNREFUSED 104.46.161.5:443 Retries left: 42
finest: [f5-cloud-failover] Function error, retrying: connect ECONNREFUSED 104.46.161.5:443 Retries left: 41
finest: [f5-cloud-failover] Listing Storage Accounts

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.10
- BIG-IP version: 16.1.2
- Cloud provider: Azure

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

5 

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jz01010101** [comment]
Ok so a private storage account is setup with a private ip on the same route table as the mgmt interface of the f5. The f5 has ext connectivity as well via mgmt interface (for testing) i can see the CFE script taking to both the private ip and an ip from the main azure storage range (not the region i have it in actually) 

When i remove this access to the extip 20.36.110.159 the script stalls at Listing storage account and complains about access to the extip above until the retry limit is reached. it does not seem to try to talk to the private ip until it has completed the connection to the extip

**Comment by shyawnkarim** [comment]
@jz01010101 are you still trying to get this to work? Just to confirm, are you using the [static definition](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#define-your-azure-network-infrastructure-objects) in your declaration?

For example:
   "externalStorage": {
    "scopingName": "myCloudFailoverStorage"
  },

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you would still like assistance.
