### ISSUE TITLE
CFE Support monitoring and failover for traffic originated from AWS DX connection instead of Public Internet

### ISSUE THREAD

**Issue by pgf999** [F5Networks/f5-cloud-failover-extension#98]
## Do you already have an issue opened with F5 support?
no

## Description
For AWS Cross AZ deployment, we need make sure the following failures F5 can monitor and fail-over to another AZ.
1.	DX to AZ
2.	AZ to AZ (be careful as I’m not sure if F5 should trigger failover in this scenario)
3.	Single AZ failure
4.	EC2 instance failure for the F5 host.

I think the current failover solution already cover 3-4 requests. However, if the original client requests just from a direct connection. It would be great if CFE can check one of the IP's availability on another side of the DX connection to ensure when DX to AZ network fails, system can successfully fail-over to another F5/AZ. Also if AZ1 to AZ2 fails, but DX to both AZs are not impacted, then the fail-over shouldn't be triggered.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: all
- BIG-IP version: all
- Cloud provider: AWS

## Severity Level
As this could impact a big number of clients, especially for existing F5 sales opportunities. AWS as F5's partner, I would suggest we can provide a solution ASAP for fulfill the client's project requirement.

Severity: <2>

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you would like additional assistance.
