### ISSUE TITLE
AWS China Support

### ISSUE THREAD

**Issue by rduchez** [F5Networks/f5-cloud-failover-extension#99]
Hello - this is more of a question - has CFE been tested in AWS China?  - I have not been able to make it work there - but might be doing it wrong. I have followed the steps found here: https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html 

CFE version: v1.11.0
BIG-IP Version: 15.1.0.4 
Severity: 4 

Desired configuration:
- Single NIC
- AWS CN (Shanghai) 
- BEST licensing
- LTM+APM+AFM provisioning

I am happy to provide the configurations as needed.  

If i do not get an answer from here withing 48 hours, i will open a ticket w/ Support for tracking. 

Thanks,  

## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version:
- BIG-IP version:
- Cloud provider:

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if needed.
